# Generated by Django 6.0.5 on 2026-05-30 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_module', models.CharField(max_length=10)),
                ('code_presentation', models.CharField(max_length=10)),
                ('module_presentation_length', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('code_module', 'code_presentation')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('region', models.CharField(max_length=100)),
                ('highest_education', models.CharField(max_length=100)),
                ('imd_band', models.CharField(blank=True, max_length=20, null=True)),
                ('age_band', models.CharField(max_length=20)),
                ('num_of_prev_attempts', models.IntegerField(default=0)),
                ('studied_credits', models.IntegerField(default=0)),
                ('disability', models.CharField(default='N', max_length=1)),
                ('final_result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Distinction', 'Distinction'), ('Withdrawn', 'Withdrawn')], max_length=20, null=True)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.module')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assessment', models.IntegerField(unique=True)),
                ('assessment_type', models.CharField(choices=[('TMA', 'Tutor Marked Assessment'), ('CMA', 'Computer Marked Assessment'), ('Exam', 'Exam')], max_length=10)),
                ('date_submitted', models.IntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(default=0)),
                ('is_banked', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='VLEActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_site', models.IntegerField()),
                ('activity_type', models.CharField(max_length=50)),
                ('date', models.IntegerField()),
                ('sum_click', models.IntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vle_activities', to='students.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vle_activities', to='students.student')),
            ],
        ),
    ]
