# Generated by Django 6.0.5 on 2026-06-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='id_assessment',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('id_assessment', 'student')},
        ),
    ]
