import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { routes } from './app.routes';
import { 
  LucideAngularModule,
  LayoutDashboard, 
  Users, 
  GraduationCap,
  BrainCircuit, 
  Bell, 
  FileUp, 
  Sparkles,
  TrendingUp, 
  UserMinus,
  Award, 
  BookOpen,
  Activity, 
  ClipboardList, 
  UserPlus, 
  Search, 
  Eye, 
  Pencil, 
  Save, 
  ChevronDown, 
  Bot, 
  RefreshCw, 
  Trash2,
  Info, 
  BellRing, 
  User, 
  Clock, 
  Check, 
  FolderOpen,
  X, 
  Upload, 
  PartyPopper, 
  Brain,
  // --- RETOUR AUX VERSIONS COMPATIBLES AVEC VOTRE PROJET ---
  AlertTriangle,  
  CheckCircle,    
  XCircle,        
  AlertCircle,    
  BarChart3,      
  Loader2,        
  Filter,         
  PlusCircle,     
  MinusCircle     
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard, 
        Users, 
        GraduationCap,
        BrainCircuit, 
        Bell, 
        FileUp, 
        Sparkles,
        TrendingUp, 
        UserMinus,
        Award, 
        BookOpen,
        Activity, 
        ClipboardList, 
        UserPlus, 
        Search, 
        Eye, 
        Pencil, 
        Save, 
        ChevronDown, 
        Bot, 
        RefreshCw, 
        Trash2, 
        Info, 
        BellRing, 
        User, 
        Clock, 
        Check, 
        FolderOpen, 
        X, 
        Upload, 
        PartyPopper, 
        Brain,
        AlertTriangle,
        CheckCircle,
        XCircle,
        AlertCircle,
        BarChart3,
        Loader2,
        Filter,
        PlusCircle,
        MinusCircle
      })
    ),
  ]
};